function data = loaddym(fname);
%
% DATA = LOADDYM(FNAME)
%
% Load a (text) result file generated by Dymola.
%
%   DATA:  Struct containing the result file matrices.
%
% Johan Åkesson 2006

fid = fopen(fname,'r');

strFound = 0;

foundEOF = 0;

l='';
lineNbr = 0;
while 1
  
  l=fgetl(fid);
%  lineNbr = lineNbr+1
  while (strcmp(l,''))
    l=fgetl(fid);
%    lineNbr = lineNbr+1
  end
  
  if (l==-1)
    break
  end
  
  d = textscan(l,'%s %[^(](%d,%d)%[^\n]','commentStyle','#');
  
  if (d{4}>0)
    ty=char(d{1});
    na=char(d{2});
    aY=d{3};
    aX=d{4};
  
    
    if (strcmp(ty,'char')),
      data.(na) = ones(aY,aX)*32;
      
      for i=1:aY,
        
	l=fgetl(fid);
%	lineNbr = lineNbr+1
	if (~strcmp(l,'')),
	  data.(na)(i,1:length(l)) = l;
	end
      end
    
      data.(na) = char(data.(na));
      
    else
      data.(na) = zeros(aY,aX);
       for i=1:aY,
	 cntd = 1;
	  tmpRow = [];
	 
	 while (cntd==1)
	   l=fgetl(fid);
%	   lineNbr = lineNbr+1
	   if (~strcmp(l,'')),
	     tmpRow = [tmpRow sscanf(l,'%f')'];
%	     length(tmpRow)
	     if (length(tmpRow)==aX)
	       data.(na)(i,:) = tmpRow;
	       cntd = 0;
	     end
	     %data.(na)(i,:) = sscanf(l,'%f');
	   end
	 end
       end
    end  
  end
end

fclose(fid);

